steps:
# Paso 1: Construir apuntando al archivo dentro de la carpeta
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tu-app', '-f', 'mi-agente adk/Dockerfile', '.']

# Paso 2: Subir la imagen al registro de Google
images:
- 'gcr.io/$PROJECT_ID/tu-app'